### ISSUE TITLE
Biogem raises Bundler::VersionConflict when locally installed version is  > 1.0.0 

### ISSUE THREAD

**Issue by ghost** [rjpbonnal/bioruby-gem#39]
Using Ruby 1.9.3-p194

Noticed that biogem raises 
/Users/george/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/bundler-1.1.5/lib/bundler/resolver.rb:246:in `resolve': Bundler could not find compatible versions for gem "bundler": (Bundler::VersionConflict)
  In Gemfile:
    bundler (~> 1.0.0) ruby

  Current Bundler version:
    bundler (1.1.5)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

**Comment by homonecloco** [comment]
I got the same issue, I even tried installing explicitly installing version 1.0.0. I tried installing explicitly version 1.0.1, but I got the same error:
n87398:public code ramirezr$ biogem fastadb
    create  .gitignore
    remove jeweler rcov lines
    create  Rakefile
    create  Gemfile
    create  LICENSE.txt
    create  README.rdoc
    create  .document
    create  lib
    create  lib/bio-fastadb.rb
    create  test
    create  test/helper.rb
    create  test/test_bio-fastadb.rb
    create  lib/bio-fastadb.rb
    create  lib/bio-fastadb
    create  lib/bio-fastadb/fastadb.rb
    create  README.rdoc
    create  README.md
    append  .gitignore
    append  .travis.yml
Jeweler has prepared your gem in bioruby-fastadb
Jeweler has pushed your repo to http://github.com/homonecloco/bioruby-fastadb
Fetching gem metadata from http://rubygems.org/........
Fetching gem metadata from http://rubygems.org/..
/Users/ramirezr/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.2.3/lib/bundler/resolver.rb:246:in `resolve': Bundler could not find compatible versions for gem "bundler": (Bundler::VersionConflict)
  In Gemfile:
    bundler (~> 1.0.0) ruby

  Current Bundler version:
    bundler (1.2.3)

This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?
    from /Users/ramirezr/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.2.3/lib/bundler/resolver.rb:161:in `start'
    from /Users/ramirezr/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.2.3/lib/bundler/resolver.rb:128:in`block in resolve'
    from /Users/ramirezr/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.2.3/lib/bundler/resolver.rb:127:in `catch'
    from /Users/ramirezr/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.2.3/lib/bundler/resolver.rb:127:in`resolve'
    from /Users/ramirezr/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.2.3/lib/bundler/definition.rb:178:in `resolve'
    from /Users/ramirezr/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.2.3/lib/bundler/definition.rb:113:in`specs'
    from /Users/ramirezr/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.2.3/lib/bundler/definition.rb:108:in `resolve_remotely!'
    from /Users/ramirezr/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.2.3/lib/bundler/installer.rb:81:in`run'
    from /Users/ramirezr/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.2.3/lib/bundler/installer.rb:14:in `install'
    from /Users/ramirezr/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.2.3/lib/bundler/cli.rb:230:in`install'
    from /Users/ramirezr/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.2.3/lib/bundler/vendor/thor/task.rb:27:in `run'
    from /Users/ramirezr/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.2.3/lib/bundler/vendor/thor/invocation.rb:120:in`invoke_task'
    from /Users/ramirezr/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.2.3/lib/bundler/vendor/thor.rb:275:in `dispatch'
    from /Users/ramirezr/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.2.3/lib/bundler/vendor/thor/base.rb:408:in`start'
    from /Users/ramirezr/.rvm/gems/ruby-1.9.2-p320/gems/bio-gem-1.3.4/bin/biogem:21:in `<top (required)>'
    from /Users/ramirezr/.rvm/gems/ruby-1.9.2-p320/bin/biogem:19:in`load'
    from /Users/ramirezr/.rvm/gems/ruby-1.9.2-p320/bin/biogem:19:in `<main>'
    from /Users/ramirezr/.rvm/gems/ruby-1.9.2-p320/bin/ruby_noexec_wrapper:14:in`eval'
    from /Users/ramirezr/.rvm/gems/ruby-1.9.2-p320/bin/ruby_noexec_wrapper:14:in `<main>'

**Comment by rjpbonnal** [comment]
Ok, I have a duty for the week end

**Comment by wwood** [comment]
Does deleting the Gemfile.lock help?
